sequenceDiagram
  autonumber
  participant SAM-BlockChain
  participant SAM-Gateway
  participant SAM-Entry-Agent
  participant Drone-Operator
  participant SafeCert
  participant SafeCert-User
  Note right of SAM-Gateway: Activated by 'conditional' entry decision
  SAM-Gateway -->> Drone-Operator: notify(decision_ID,evidence_required)
  Drone-Operator ->> SafeCert: generate_evidence(evidence_required)
  SafeCert ->> SafeCert: extract_relevant_claims()
  SafeCert ->> SafeCert: check_satisfaction()
  loop until-satisfied
    SafeCert->>SafeCert-User: display_results()
    SafeCert-User->>SafeCert: updateSafetyCases()
    SafeCert ->> SafeCert: extract_relevant_claims()
  end
  SafeCert ->> Drone-Operator: sendCertificate(updated_safety_case, attestation)
  Drone-Operator ->> SAM-Gateway: requestEntry(updated_safety_case,attestation)
  SAM-Gateway ->> SAM-BlockChain: generateHash(updated_safety_case,attestation)
  SAM-BlockChain -->> SAM-Gateway: return(hash)
  SAM-Gateway ->> SAM-Entry-Agent: requestEntry(ActionID,attestation)
  SAM-Entry-Agent ->> SAM-Entry-Agent: make_entry_decision(decision_ID,attestation)
  SAM-Entry-Agent -->>SAM-Gateway: return(Approved|Denied|Conditional)
  SAM-Gateway ->> Drone-Operator: notify_decision(Approved|Denied|Conditional)
