sequenceDiagram
  autonumber
  participant SAM-BlockChain
  participant SAM-Gateway
  participant Drone|GCS
  participant SafeCert
  participant Operator
  SAM-Gateway -->> Drone|GCS: ACTION-REQUIRED(ActionID, evidence_needed)
  Drone|GCS->> SafeCert: generate_evidence(safety-case, evidence_needed)
  SafeCert ->> SafeCert: extract_claims()
  SafeCert ->> Operator: display_results()
  Operator ->> Operator: inspect()
  loop 
    Operator->>SafeCert: updateSafetyCase()
    SafeCert->>SafeCert: analyzeSafetyCase()
    SafeCert -->> Operator: displayUpdates()
    Operator ->> Operator: inspectResult()
  end
  SafeCert ->> Drone|GCS: sendCertificate(safety_case, attestation)
  Drone|GCS ->> SAM-Gateway: requestEntry(safety_case,attestation)
  SAM-Gateway ->> SAM-BlockChain: generateHash(safety_case,attestation)
  SAM-BlockChain -->> SAM-Gateway: HASH
  SAM-Gateway ->> SAM-Entry-Agent: requestEntry(ActionID,attestation)
  SAM-Entry-Agent ->> SAM-Entry-Agent: Analysis_and_Decision(evidence_needed,attestation)
  SAM-Entry-Agent -->>SAM-Gateway: APPROVED|DENIED|ACTION-REQUIRED
  SAM-Gateway --> Drone|GCS: APPROVED|DENIED|ACTION-REQUIRED
